camera_topics:
  front:
    #image_topic: "/zed2/zed_node/rgb_raw/image_raw_color_throttle" #"/spot/camera/hand_color/image"
    #info_topic: "/zed2/zed_node/rgb_raw/camera_info" #"/spot/camera/hand_color/camera_info"
    image_topic: "/spot/camera/hand_color/image"
    info_topic: "/spot/camera/hand_color/camera_info"
    use_for_training: true
    publish_confidence: true
    publish_input_image: true
    scheduler_weight: 1
  
# Provides 1080 (height) x 1920 (width) images
network_input_image_height: 224 # 448
network_input_image_width: 224 # 448
